[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"
default-run = "aoc2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.2.1"
glob = "0.3.1"
itertools = "0.12.0"
num = "0.4.1"
